apiVersion: servarr.dev/v1alpha1
kind: ServarrApp
metadata:
  name: ssh-bastion
spec:
  app: SshBastion
  appConfig:
    sshBastion:
      enablePasswordAuth: false
      tcpForwarding: false
      gatewayPorts: false
      users:
        - name: testuser
          uid: 1000
          gid: 1000
          mode: restricted-rsync
          restrictedRsync:
            allowedPaths:
              - /opt
          publicKeys: |
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAItest test@example.com
