pub mod bazarr;
pub mod cleanuparr;
mod client;
pub mod cross_app_sync;
pub mod health;
pub mod houndarr;
pub mod jellyfin;
pub mod k8s;
pub mod maintainerr;
pub mod plex;
pub mod prowlarr;
pub mod sabnzbd;
pub mod seerr;
pub mod servarr_v3;
pub mod tautulli;
mod tenant_safe_message;
#[cfg(test)]
mod test_support;
pub mod transmission;

pub use bazarr::BazarrClient;
pub use cleanuparr::CleanuparrClient;
pub use client::{ApiError, HttpClient};
pub use cross_app_sync::{CrossAppSync, RegisteredArrInstance};
pub use health::HealthCheck;
pub use houndarr::HoundarrClient;
pub use jellyfin::JellyfinClient;
pub use k8s::{SecretError, read_secret_key};
pub use maintainerr::MaintainerrClient;
pub use plex::PlexClient;
pub use prowlarr::ProwlarrClient;
pub use sabnzbd::SabnzbdClient;
pub use seerr::SeerrClient;
pub use servarr_v3::{AppKind, ServarrClient};
pub use tautulli::TautulliClient;
pub use tenant_safe_message::TenantSafeMessage;
pub use transmission::{BasicCredentials, DeleteLocalData, TorrentInfo, TransmissionClient};
