use serde::Deserialize;
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize)]
struct AppImageConfig {
    repository: String,
    tag: String,
    port: i32,
    security: String,
    downloads: bool,
    probe_path: Option<String>,
    probe_type: Option<String>,
}

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let toml_path = Path::new(&manifest_dir)
        .parent() // crates/
        .unwrap()
        .parent() // repo root
        .unwrap()
        .join("image-defaults.toml");

    println!("cargo::rerun-if-changed={}", toml_path.display());

    let contents = fs::read_to_string(&toml_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", toml_path.display()));

    let apps: BTreeMap<String, AppImageConfig> = toml::from_str(&contents)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", toml_path.display()));

    let out_dir = env::var("OUT_DIR").unwrap();
    let out_path = Path::new(&out_dir).join("image_defaults.rs");

    let mut code = String::new();
    code.push_str("// Generated by build.rs from image-defaults.toml — do not edit.\n\n");
    code.push_str("pub(crate) struct AppImageDefaults {\n");
    code.push_str("    pub repository: &'static str,\n");
    code.push_str("    pub tag: &'static str,\n");
    code.push_str("    pub port: i32,\n");
    code.push_str("    pub security: &'static str,\n");
    code.push_str("    pub downloads: bool,\n");
    code.push_str("    pub probe_path: &'static str,\n");
    code.push_str("    pub probe_type: &'static str,\n");
    code.push_str("}\n\n");
    code.push_str("pub(crate) fn image_defaults(app: &str) -> Option<AppImageDefaults> {\n");
    code.push_str("    match app {\n");

    for (name, cfg) in &apps {
        let probe_path = cfg.probe_path.as_deref().unwrap_or("/");
        let probe_type = cfg.probe_type.as_deref().unwrap_or("http");
        code.push_str(&format!(
            "        {name:?} => Some(AppImageDefaults {{\n\
             \x20           repository: {:?},\n\
             \x20           tag: {:?},\n\
             \x20           port: {},\n\
             \x20           security: {:?},\n\
             \x20           downloads: {},\n\
             \x20           probe_path: {:?},\n\
             \x20           probe_type: {:?},\n\
             \x20       }}),\n",
            cfg.repository, cfg.tag, cfg.port, cfg.security, cfg.downloads, probe_path, probe_type,
        ));
    }

    code.push_str("        _ => None,\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    fs::write(&out_path, code).unwrap();
}
